declare function postData(url: string, params: {}, cb: Function): void;
declare var root: HTMLElement | null;
declare function render(params: string): void;
declare var listAddFriendRequest: HTMLElement | null;
declare var findNameFriends: HTMLElement | null;
declare var submitFindNameFriends: HTMLElement | null;
declare var idFriend: HTMLElement | null;
declare var submitIdFriend: HTMLElement | null;
declare var listAddFriendRequest: HTMLElement | null;
declare var CacelAddFriendRequest: HTMLElement | null;
declare var SubmitCacelAddFriendRequest: HTMLElement | null;
declare var AcceptAddFriendRequest: HTMLElement | null;
declare var SubmitAcceptAddFriendRequest: HTMLElement | null;
declare var SubmitBoxChatList: HTMLElement | null;
declare var cancelFriends: HTMLElement | null;
declare var SubmitCancelFriends: HTMLElement | null;
declare var HiddenBoxChat: HTMLElement | null;
declare var SubmitHiddenBoxChat: HTMLElement | null;
declare var Chat: HTMLElement | null;
declare var SubmitChat: HTMLElement | null;
declare var SubmitSentFriendRequest: HTMLElement | null;
declare var GetContentInBox: HTMLElement | null;
declare var SubMitGetContentInBox: HTMLElement | null;
