declare function postData(url: string, params: {}, cb: Function): void;
declare function xml(url: string, params: {}, cb: Function, method?: string): void;
declare var root: HTMLElement | null;
declare function render(params: string): void;
declare var listAddFriendRequest: HTMLElement | null;
declare var findNameFriends: HTMLInputElement;
declare var submitFindNameFriends: HTMLElement | null;
declare var idFriend: HTMLInputElement;
declare var submitIdFriend: HTMLElement | null;
declare var listAddFriendRequest: HTMLElement | null;
declare var CacelAddFriendRequest: HTMLInputElement;
declare var SubmitCacelAddFriendRequest: HTMLElement | null;
declare var AcceptAddFriendRequest: HTMLInputElement;
declare var SubmitAcceptAddFriendRequest: HTMLElement | null;
declare var SubmitBoxChatList: HTMLInputElement;
declare var cancelFriends: HTMLInputElement;
declare var SubmitCancelFriends: HTMLElement | null;
declare var HiddenBoxChat: HTMLInputElement;
declare var SubmitHiddenBoxChat: HTMLElement | null;
declare var Chat: HTMLInputElement;
declare var SubmitChat: HTMLElement | null;
declare var SubmitSentFriendRequest: HTMLElement | null;
declare var GetContentInBox: HTMLInputElement;
declare var SubMitGetContentInBox: HTMLElement | null;
declare var password: HTMLInputElement;
declare var password1: HTMLInputElement;
declare var password2: HTMLInputElement;
declare var idHiddenMess: HTMLInputElement;
